if ((Get-ProcessorBits 32) -or $env:ChocolateyForceX86 -eq $true) { $MinGWArch = "32" } else { $MinGWArch = "64" }
$MinGWMMVer = "81"
$QtSDKVer = "5.15.2"
$QtSDKMVer = "5"
$QtSDKMMPVer = "5152"
$QtSDKRoot = "C:\Qt"
$QtSDKPath = "$QtSDKRoot\$QtSDKVer"
$QtSDKMinGWPath = "$QtSDKRoot\$QtSDKVer\mingw$MinGWMMVer`_$MinGWArch"
$CMakeRegistryPath = "HKCU:\SOFTWARE\Kitware\CMake"
$CMakeSystemRepositoryPath = "HKLM:\SOFTWARE\Kitware\CMake\Packages"
$CMakePackageName = "Qt$QtSDKMVer"
